apiVersion: v2
appVersion: 1.33.7
description: A Helm chart to run Azure CSI driver for Azure Disks.
icon: https://s.giantswarm.io/app-icons/azure/1/dark.svg
home: https://github.com/giantswarm/azuredisk-csi-driver-app
name: azuredisk-csi-driver-app
version: 2.1.0-dev
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
  compatibleProviders: [azure]
annotations:
  application.giantswarm.io/team: phoenix
  io.giantswarm.application.team: phoenix
